### ISSUE TITLE
Proposal to add a proxy option via code injection

### ISSUE THREAD

**Issue by twilson63** [atomify/atomify#41]
Hey Atomify Team,

Great Work!  

We are building standalone applets or components using atomify and it is working great!  Thank you so much for this tool!  We bumped into a use case where during development we want to focus on the application but leverage our custom api using simple proxy.  

So we added a simple override:

https://gist.github.com/akennedy/26b0fa5937dad5318d64

```
 server: {
    proxy: {
      matcher: /^\/api|autocompletes|clinical/,
      handler: function(req,res) {
        return httpProxy.createProxyServer().web(req, res, { target: 'http://localhost:3000' });
      }
    },
    st: {
      path: './www',
      cache: false
    },
```

Would you be open to a PR adding the ability to inject a proxy handler for server-side apis?

If so, I will send you a PR.

Cheers!  Great Work!

Tom

**Comment by joeybaker** [comment]
This was fixed in #48
