### ISSUE TITLE
Atomify Logo + Github Page to present atomify?

### ISSUE THREAD

**Issue by serapath** [atomify/atomify#69]

**Comment by joeybaker** [comment]
@serapath we really need a website, but it looks like you might have found the logo here? https://github.com/atomify

**Comment by serapath** [comment]
yes, i was designing a crappy logo - then i figured out, there is one already.
Am doing now the presentation using that logo :-)
I will probably put it on serapath.github.io/atomify

**Comment by joeybaker** [comment]
That's awesome!

**Comment by serapath** [comment]
I will soon include some slides about using variables for creating themes.
