### ISSUE TITLE
have the option to make the server to be SPA server

### ISSUE THREAD

**Issue by borisirota** [atomify/atomify#71]
Hey,

I'm using atomify with angular and using the development server as a SPA server.

Currently, I have post install hook that adds to the beginning [createServer function](https://github.com/atomify/atomify/blob/master/lib/server.js#L98) the following code:
```javascript
var dirs = req.url.split('/');
if (dirs[dirs.length - 1].indexOf('.') === -1) { //not file
    req.url = '/';
}
```

It will be great to convert the server to be SPA server by setting some option to be `true`.

Thanks

**Comment by bclinkinbeard** [comment]
I'd be hesitant to hardcode any logic like that, but maybe we could add a hook that would allow users to specify custom logic for handling requests? In the meantime, you can just turn html5mode off in your Angular app.

**Comment by borisirota** [comment]
@bclinkinbeard Well I guess it a good solution to whom using it through javascript but how to add support for that from the command line (I use it this way :) ) ?

**Comment by borisirota** [comment]
added in 7.1.0

**Comment by joeybaker** [comment]
Thanks @borisirota!

**Comment by borisirota** [comment]
:smile:

@joeybaker The SPA mode doesn't support assets. It seems to me that its possible to add a flag (--serve-assets for example) which checks if the path is a file's path so call to `mount(req, res)`.

Maybe something like this [here](https://github.com/atomify/atomify/blob/master/lib/server.js#L304):  

```javascript
    ...
    var dirs = req.url.split('/');
    var isFile = dirs[dirs.length - 1].indexOf('.') !== -1;

    if (spaMode) {
        if (serveAssets && isFile) mount(req, res)
        else internals.serveDefaultPage(req, res, args)
    }
    else if (handler(req, res, args)) return null
    else mount(req, res)
    ...
```

In all my use cases, if the path is a file I need to serve the original file (image, video, etc.), otherwise the index.html.

Is it just me ? Is it too specific ? What do think ?

**Comment by joeybaker** [comment]
@borisirota hmmm… yea. that's a bug :( Opened https://github.com/atomify/atomify/issues/81

**Comment by borisirota** [comment]
@joeybaker Cool Thanks :)
