### ISSUE TITLE
in the new version 6.1.0 the server reloads the browser continuously

### ISSUE THREAD

**Issue by borisirota** [atomify/atomify#72]
In the previous version I didn't provide output (no js and no css) in development through the options and it worked ok.
Now, an output [must be provided](https://github.com/atomify/atomify/blob/master/lib/cli.js#L38) in order to load the server (is it really necessary?) and sometimes it gets into a loop of browser reloading. Not sure why this is happening but I see that it catches the js output as changed (no action by my side) and this is the trigger for the reload.

**Comment by joeybaker** [comment]
@borisirota hmmm… I'm not able to repro. Can you provide a test-case?

**Comment by borisirota** [comment]
@joeybaker Sure.

1. download [boilerplate-node-module-angular](https://github.com/borisirota/boilerplate-node-module-angular)
2. `npm install`
3. `npm start`

Check out the build script inside `package.json` in order to understand the input.

You can see at the beginning that it reloads itself few times. In addition, play with that a little bit (save the lib/controller.js file for example). You should wait sometimes for the next reload. This behavior isn't deterministic and sometimes it gets into infinite loop of reloading.

*******

Few notes:
1. I'm running it in watch mode. maybe issues with watchify and gaze?
2. This is version 6.1.0. when output provided (`-o build/assets/bundle` inside the build script) there is a problem in version 6.0.5 as well but not in that frequency of reloads. In addition, this happens if output is provided to the css only.
3. In version 6.0.5, if output not provided everything works as expected. In version 6.1.0, a css output must be provided in order to start the server.
4. When in infinite loop, cpu gets crazy.
5. `package.json` is being watched as well and the bundle is being updated after change in it. The patterns provided to gaze not include `package.json` so how its being watched ?

![screen shot 2015-03-25 at 2 28 11 pm](https://cloud.githubusercontent.com/assets/5683472/6825765/74cac7e4-d305-11e4-87cb-7291ddc285a9.png)

*******

Some screen shots of logs:

* server on launch:

![screen shot 2015-03-25 at 2 12 15 pm](https://cloud.githubusercontent.com/assets/5683472/6825609/6aaabf18-d304-11e4-9a03-0029c8158afb.png)

* after controller.js save:

![screen shot 2015-03-25 at 2 16 28 pm](https://cloud.githubusercontent.com/assets/5683472/6825579/2b696796-d304-11e4-80c0-6529e789a1cd.png)

* infinite loop:

![screen shot 2015-03-25 at 2 34 14 pm](https://cloud.githubusercontent.com/assets/5683472/6825591/4b3ad0a0-d304-11e4-842f-2ce573186b16.png)
![screen shot 2015-03-25 at 2 34 31 pm](https://cloud.githubusercontent.com/assets/5683472/6825595/4f3a2764-d304-11e4-8245-841aa2ebe4ee.png)
![screen shot 2015-03-25 at 2 34 46 pm](https://cloud.githubusercontent.com/assets/5683472/6825598/51ff5a28-d304-11e4-915e-1ec73d3ed694.png)

**Comment by borisirota** [comment]
BTW I'm using node v0.10.21

**Comment by joeybaker** [comment]
@borisirota I think I see the issue. [6.1.0 added built-in css watch mode](https://github.com/atomify/atomify/blob/master/CHANGELOG.md#610), which is giving you the infinite loop because you're watching the directory that the output is going into.

**Comment by borisirota** [comment]
@joeybaker hmmm what do you mean by "you're watching the directory that the output is going into" ? isn't it some internal mechanism ? can I disable it ?

**Comment by borisirota** [comment]
@joeybaker If it was possible to run the server without specify the css output (like in version 6.0.5), then this directory won't be updated with new files or existing file updates (because the bundle.js and bundle.css are created [on the fly](https://github.com/atomify/atomify/blob/master/lib/server.js#L101))

**Comment by joeybaker** [comment]
Good point. @serapath what do you think?

**Comment by serapath** [comment]
i read through it when i saw the issue, but i'm not sure what the problem is.
@borisirota what is your code exactly doing that triggers the reload?
Do you manipulate the bundle files after they have been created?
If so, why do you do that outside of atomify (because wouldnt "the correct way" of doing whatever you do be to use either a rework plugin or a browserify transform)?

**Comment by borisirota** [comment]
@serapath everything happens "inside" atomify. Check my second comment and you can try by yourself :) -> its a boilerplate module with few lines of code.

I'm pretty sure that its not the code that triggers the reload (the code does nothing - its only angular on the client side).
After I run atomify ('npm start' - invokes the live reload server) it reloads itself few times with no action by my side (the first screenshot in the series). Then, the next multiple reloads happen after I save a file in the bundle (controller.js - the second screen shot). And sometimes after a save it gets into infinite loop of reloads (third screen shot).

Thanks for your help :)

**Comment by serapath** [comment]
can't reproduce.
"npm start" fails
```
> boilerplate-node-module-angular@0.0.1 start /home/serapath/workspace/codingamigos/EXPERIMENTS/boilerplate-node-module-angular
> npm run build -s


  rendered build/index.html


events.js:141
      throw er; // Unhandled 'error' event
            ^
Error: watch ENOSPC
```

 and tells me i should run "npm run build -s", which also fails with

```
  rendered build/index.html


events.js:141
      throw er; // Unhandled 'error' event
            ^
Error: watch ENOSPC
```

I don't know what this is about.
any idea?

**Comment by borisirota** [comment]
@serapath it seems that ENOSPC means that there is no space on the drive.

[node-js-error-enospc](http://stackoverflow.com/questions/22475849/node-js-error-enospc)
[grunt-watch-error-waiting-fatal-error-watch-enospc](http://stackoverflow.com/questions/16748737/grunt-watch-error-waiting-fatal-error-watch-enospc)

`npm start` works ok and the second line `npm run build -s` means that it run the build script so I guess its only a free space issue -> you can delete the `-s` from the `npm run build -s` in order to see the full error stack.

**Comment by serapath** [comment]
hm, i have plenty of disc space left. I don't get that with other projects in my workspace folder.
Your first link solved the issue and i could start your project. The first link reminds me of a problem i once had with dropbox, when it contained to many folders and files that had to be watched and i also figured out why, because there is a problem with your `package.json` file.

1. you set [ -e . ...] which i dont know what exactly it does, because there is not "index.js" file in the root folder, but only in `lib/index.js`, so i guess it's watching everything, which includes the `node_modules` folder and that means lots of files, thats why i got the error message.

2. So when i replaced `-e .` with `-e lib/index.js`, page still opens and nothing reloads and also the problem with watching to many files goes away :-)

Hope it solves it for you too.

**Comment by borisirota** [comment]
@serapath WOW that was the problem !!!

`-e` is the entry point for browserify. When I did it, I was sure that if its a directory, it will check the package.json#main if `index.js` not exists in order to find the real entry point (wanted to make it dynamic and not hardcoded) -> I was wrong.

I guess I was so much in it so I needed someone from the outside :)

Thanks a lot !!!

**Comment by joeybaker** [comment]
Thanks for tracking that down @serapath!!
