### ISSUE TITLE
atomify breaks in server mode (problem with browser sync)

### ISSUE THREAD

**Issue by serapath** [atomify/atomify#80]
See change [browser-sync to 2.7.3](https://github.com/BrowserSync/browser-sync/commit/d7c96e4fd4089d05952644a4213d1a95b4b6fa0e) broke atomify

Error exists not with < 2.7.3
```bash
...browser-sync/lib/file-watcher.js:47
her = watch(item.match, item.options || defaultWatchOptions, item.fn.bind(bs.p
                                                                    ^
TypeError: Cannot read property 'bind' of undefined
...
```
We use `browser-sync@^2.6.4` which downloads now `2.7.4` which breaks atomify when run in server mode.

**Comment by serapath** [comment]
`browser-sync@2.7.5` just fixed the issue. :-) yay

**Comment by joeybaker** [comment]
:easy_button: ;)
